apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/component: frontend
    app: employees
spec:
  ports:
  - port: 8080
  selector:
    app.kubernetes.io/name: application
    app.kubernetes.io/component: frontend
    app: employees