apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend
    app: employees
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: employees
      app.kubernetes.io/component: frontend
      app: employees
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: employees
        app.kubernetes.io/component: frontend
        app: employees
    spec:
      containers:
      - name: employees
        image: 850113952307.dkr.ecr.us-east-1.amazonaws.com/app-repository:v0.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DBHOST
          value: mysql
        - name: DBPORT
          value: '3306'
        - name: DBUSER
          value: 'root'
        - name: DATABASE
          value: 'employees'
        - name: DBPWD
          value: db_pass123
        ports:
        - containerPort: 8080